import commonStyles from '~/styles/CommonStyles.module.css'
import typographyStyles from '~/styles/Typography.module.css'
import frontpageStyles from './Frontpage.module.css'

export default function TermsOfUsage () {
  return (
    <div className={`${commonStyles.typographyBody} ${typographyStyles.textLeft}`}>
      <h3 className={`${commonStyles.typographyBodySemiBold} ${frontpageStyles.modalMargin}`}>Platformatic <span class={commonStyles.bold}>&quot;Early Adopter&quot;</span> Terms of Use</h3>
      <p>Last Modified: May 30th, 2023</p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Acceptance of the Terms of Use</p>
      <p>These Terms of Use are entered into by and between you and Platformatic, Inc. (<span class={commonStyles.bold}>&quot;Company&quot;</span>,<span class={commonStyles.bold}>&quot;our&quot;</span>,<span class={commonStyles.bold}>&quot;we&quot;</span>, or <span class={commonStyles.bold}>&quot;us&quot;</span>). The following Terms of Use (<span class={commonStyles.bold}>&quot;Terms&quot;</span>) govern your access to and use of <a href='https://platformatic.dev' target='_blank' className={commonStyles.applyHoverUnderline} rel='noreferrer'>https://platformatic.dev</a>  (the <span class={commonStyles.bold}>&quot;Site&quot;</span>), including any subpages, content, functionality, and services offered on or through the Site, including our Platformatic Cloud offerings available at https://platformatic.cloud (collectively the <span class={commonStyles.bold}>&quot;Services&quot;</span>), whether as a guest or a registered user.</p>
      <p>THESE TERMS CONTAIN A MANDATORY ARBITRATION CLAUSE THAT REQUIRES THE USE OF ARBITRATION ON AN INDIVIDUAL BASIS TO RESOLVE DISPUTES, RATHER THAN JURY TRIAL OR CLASS ACTIONS.</p>
      <p>Please read the Terms carefully before you start to access or use the Site or Services. By accessing or using the Site or Services or by clicking to accept or agree to these Terms when this option is made available to you, you accept and agree to be bound and abide by these Terms. If you do not want to agree to these Terms, you must not access or use the Site or our Services.</p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Changes to these Terms</p>
      <p>We may revise and update these Terms from time to time in our sole discretion. All changes are effective immediately when we post them, and apply to all access to and use of the Site and Services thereafter. However, any changes to the dispute resolution provisions set out in the Governing Law and Jurisdiction sections below will not apply to any disputes for which the parties have actual notice on or before the date the change is posted. The date these Terms were last updated is identified at the top of the page.</p>
      <p>Your continued access to and use of the Site or our Services following the posting of revised Terms means that you accept and agree to the changes. You are expected to check this page from time to time so you are aware of any changes, as they are binding on you.</p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Age Requirements</p>
      <p>Our Site and Services are offered and available to users who are 18 years of age or older. By accessing or using either the Site or our Services, you represent and warrant that you are of legal age to form a binding contract with us and you meet all of the foregoing eligibility requirements. If you do not meet all of these requirements, you must not access or use the Site or Services. </p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Accessing the Site</p>
      <p>We reserve the right to withdraw or amend our Site and Services, in our sole discretion without notice. We will not be liable if for any reason all or any part of the Site or Services are unavailable at any time or for any period. From time to time, we may restrict access to some or all parts of the Site and the Services we offer.</p>
      <p>You are responsible for making all arrangements necessary for you to have access to the Site and Services, and for ensuring that all persons who access the Site and Services through your internet connection are aware of these Terms and comply with them.</p>
      <p>To access the Site or Services, or some of the resources offered in connection with the Site and Services, you may be asked to provide certain registration details or other information. It is a condition of your access to and use of the Site and Services that all the information you provide on or in connection with the Site or Services be correct, current, and complete. </p>
      <p>The Company, its affiliates and their respective third party service providers may need to provide you with certain communications, notices, agreements, statements or disclosures in writing regarding the Site and Services.  You acknowledge that information and communications transmitted via the Site and Services are generally transmitted via the Internet and may be routed via public, transnational installations which are not specifically protected. We cannot guarantee that any information or communications so transmitted will be completely protected against unauthorized access. By accessing the Site and/or using the Services, you are accepting those associated risks. </p>
      <p>By providing us with your email address or other contact information, you agree that we may communicate with you about the Site and Services electronically. Standard messaging and data rates may apply to such communications and you are responsible for any such fees. If at any time you no longer wish to receive electronic communications from us, you may unsubscribe via the link in the electronic communication, or you may contact <a href='mailto:support@platformatic.dev?subject=Unsubscribe'>support@platformatic.dev</a>. We reserve the right to limit access to the Site and/or Services if you withdraw your consent to receive electronic communications.  </p>
      <p>You acknowledge and agree that all information you provide to register on our Site or to use our Services or otherwise, including, but not limited to, through the use of any interactive features on the Site, is governed by our Privacy Notice, and you agree to all actions we take with respect to your information consistent with our Privacy Notice.</p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Account Security</p>
      <p>To access or use our Services you must create an account with us. When you create an account, you must provide accurate and up-to-date information. It is important that you maintain and promptly update your details and any other information you provide to us, to keep such information current or complete. You also acknowledge that your account is personal to you and agree not to provide any other person with your user name, password, or other security information. </p>
      <p>You agree to notify us immediately of any unauthorized access to or use of your user name or password or any other breach of security. You also agree to ensure that you exit from your account at the end of each session. You should use particular caution when accessing your account from a public or shared computer so that others are not able to view or record your password or other personal information.</p>
      <p>We have the right to disable any user name, password, or other identifier, whether chosen by you or provided by us, at any time in our sole discretion for any or no reason, including if, in our opinion, you have violated any provision of these Terms.</p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Suspension and Termination</p>
      <p>In addition to all other rights and remedies we may have, we reserve the right to suspend, terminate or otherwise deny your access to or use of all or any part of the Site or Services, with or without notice to you and without incurring any resulting obligation or liability, if (a) we receive a judicial or other governmental demand or order, subpoena or law enforcement request that expressly, or we reasonably believe, requires us to do so, or (b) we believe in our sole discretion that you have failed to comply with these Terms or you are, have been, or are likely to be involved in any fraudulent, misleading or unlawful activities.</p>
      <p>You may terminate these Terms at any time and for any reason by discontinuing all use of the Site and Services and notifying us by [method].</p>
      <p>Upon any termination of these Terms, you must promptly destroy all originals and copies of any materials relating to or referencing the Site or the Services that are in your possession or control. </p>
      <p>Notwithstanding termination of these Terms, the terms and conditions governing your indemnification obligations, prohibited uses, the disclaimers of warranties, the limitation of our liability and any other provision which by its nature is intended to survive termination will survive such termination. </p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Fees and Payment</p>
      <p>Access to and use of the Services may require you to pay a subscription fee for the duration of your subscription. You may terminate your subscription at any time by following the termination procedures outlined in these Terms. By purchasing a subscription to a paid Service, you are expressly agreeing that we are permitted to bill you for the applicable fees, any applicable taxes and other charges you may incur in connection with your use of the Service(s) and that such fees will be billed to the credit card you provide in accordance with the billing terms in effect at the time the fee or charge is due and payable. If payment is not received or cannot be charged to your credit card for any reason prior to the applicable subscription period, we reserve the right to either suspend or terminate your access to the Service(s). All subscription fees are payable in US Dollars and based on the Service(s) purchased, not on actual usage. All fees are non-refundable. Subscription fees for paid Services will be billed in advance on a [monthly/annual] basis. There will be no refunds or credits for partial months of service. Your subscription to the paid Service(s) will automatically renew for additional, successive subscription periods equal in duration to the subscription period you initially purchased unless you terminate your subscription prior to the end of the then-current subscription period. You acknowledge and agree that we may automatically charge the credit card that we have on record for you for all subscription renewals and you agree to promptly update us in the event that such credit card is no longer valid. </p>
      <p>All fees or other amounts owed by you are exclusive of taxes and similar assessments and you are solely responsible for all sales, use and other similar taxes, duties and charges of any kind imposed by any federal, state or local government or regularly authority.</p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Intellectual Property Rights</p>
      <p>The Site, its entire contents, features, and functionality (including but not limited to all information, software, text, displays, images, video, and audio, and the design, selection, and arrangement thereof) and our Services are owned by the Company, its licensors, or other providers of such material and are all protected by United States and international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.</p>
      <p>These Terms permit you to access and use the Site and our Services for your personal, non-commercial use only. You must not reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store, or transmit any of the material on our Site or our Services. </p>
      <p>If you copy, modify, download, or otherwise use or provide any other person with access to any part of the Site or Services in breach of these Terms, your right to access and use the Site and Services will stop immediately and you must, at our option, return or destroy any copies of the materials you have made. No right, title, or interest in or to the Site or the Services, or any content on the Site or available through the Services, is transferred to you, and all rights not expressly granted are reserved by the Company. Any use of the Site or Services not expressly permitted by these Terms is a breach of these Terms and may violate copyright, trademark, and other laws.</p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Trademarks</p>
      <p>The Company’s name, Platformatic, and all related names, logos, product and service names, designs, and slogans are trademarks of the Company or its affiliates or licensors. You must not use such marks without the prior written permission of the Company. All other names, logos, product and service names, designs, and slogans on the Site and services are the trademarks of their respective owners.</p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Prohibited Uses</p>
      <p>You may use the Site or Services only for lawful purposes and in accordance with these Terms. You agree not to access or use the Site or Services, directly or indirectly:</p>
      <ul className={frontpageStyles.modalUl}>
        <li>In any way that violates any applicable federal, state, local, or international law or regulation (including, without limitation, any laws regarding the export of data or software to and from the US or other countries). </li>
        <li>For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way by exposing them to inappropriate content, asking for personally identifiable information, or otherwise.</li>
        <li>To transmit, or procure the sending of, any advertising or promotional material without our prior written consent, including any &quot;junk mail&quot;, &quot;chain letter&quot;, &quot;spam&quot; or any other similar solicitation.</li>
        <li>To impersonate or attempt to impersonate the Company, a Company employee, another user, or any other person or entity (including, without limitation, by using email addresses or screen names associated with any of the foregoing).</li>
        <li>To engage in any other conduct that restricts or inhibits anyone’s use or enjoyment of the Site or Services, or which, as determined by us, may harm the Company or users of the Site or Services, or expose us or them to liability.</li>
      </ul>
      <br />
      <p>Additionally, you agree not to, directly or indirectly:</p>
      <ul className={frontpageStyles.modalUl}>
        <li>Copy, modify or create derivative works or improvements of the Site or Services.</li>
        <li>Rent, lease, lend, sell, sublicense, assign, distribute, publish, transfer or otherwise make any portion of the Site or Services available to any other person, including on or in connection with the Internet or any timesharing, service bureau, software-as-a-service, cloud or other technology or service.</li>
        <li>Reverse engineer, disassemble, decompile, decode, adapt or otherwise attempt to derive or gain access to the source code of the Site or Services, in whole or in part, without our prior written consent or the consent of our licensors, as applicable.</li>
        <li>Bypass or breach any security device or protection used by the Site or Services, or access or use the Site or Services other than as permitted by these Terms.</li>
        <li>Use the Site or Services in any manner that could disable, overburden, damage, or impair the Site or Services, or that interferes with any other party’s use of the Site or Services.</li>
        <li>Use any robot, spider, or other automatic device, process, or means to access the Site or Services for any purpose, including monitoring or copying any of the material on the Site or Services.</li>
        <li>Use any manual process to monitor or copy any of the material on the Site or Services, or for any other purpose not expressly authorized in these Terms, without our prior written consent.</li>
        <li>Use any device, software, or routine that interferes with the proper working of the Site or Services.</li>
        <li>Introduce, input, upload, transmit or otherwise provide to the Site or through the Services any information or materials that are unlawful or injurious, or contain, transmit or activate any harmful code, such as any viruses, Trojan horses, worms, logic bombs, or other material that is malicious or technologically harmful.</li>
        <li>Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of the Site or Services, the servers or networks on which the Site or Services are hosted, or any server, computer, or database connected to the Site or Services. </li>
        <li>Attack the Site or Services via a denial-of-service attack or a distributed denial-of-service attack.</li>
        <li>Otherwise attempt to interfere with the proper working of the Site or Services.</li>
        <li>Access or use the Site or Services for purposes of competitive analysis of the Site or Services, the development, provision or use of a competing software service or product or any other purpose that is to our detriment or commercial disadvantage.</li>
        <li>Access or use the Site or Service in, or in association with, the design, construction, maintenance or operation of any hazardous environments, systems or applications, any safety response systems or other safety-critical applications, or any other use or application in which the use or failure of the Site or Services could lead to personal injury or severe physical or property damage.</li>
      </ul>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Reliance on Information Posted</p>
      <p>The information presented on or through the Site and Services is made available solely for general information purposes. We do not warrant the accuracy, completeness, or usefulness of this information. Any reliance you place on such information is strictly at your own risk. We disclaim all liability and responsibility arising from any reliance placed on such materials by you or any other visitor to the Site or user of the Services, or by anyone who may be informed of any of its contents.</p>
      <p>The Site and Services may include content, products and services provided by third parties, including materials provided by other users, bloggers, and third-party licensors, syndicators, aggregators, and/or reporting services. All statements and/or opinions expressed in these materials, and all articles and responses to questions and other content, other than the content provided by the Company, are solely the opinions and the responsibility of the person or entity providing those materials. These materials do not necessarily reflect the opinion of the Company. We are not responsible, or liable to you or any third party, for the content or accuracy of any materials provided by any third parties.</p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Changes to the Site or Services</p>
      <p>We may update the Site and the Services from time to time, but the Site and Services are not necessarily complete or up-to-date. Any of the material on the Site or available through the Services may be out of date at any given time, and we are under no obligation to update such material. </p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Linking to the Site and Social Media Features</p>
      <p>You may link to our Site, provided you do so in a way that is fair and legal and does not damage our reputation or take advantage of it, but you must not establish a link in such a way as to suggest any form of association, approval, or endorsement on our part. </p>
      <p>The Site may provide certain social media features that enable you to:</p>
      <ul className={frontpageStyles.modalUl}>
        <li>Link from your own or certain third-party websites to certain content on the Site.</li>
        <li>Send emails or other communications with certain content, or links to certain content, on the Site.</li>
        <li>Cause limited portions of content on the Site to be displayed or appear to be displayed on your own or certain third-party websites.</li>
      </ul>
      <p>You may use these features solely as they are provided by us and solely with respect to the content they are displayed with, and otherwise in accordance with any additional terms and conditions we provide with respect to such features. Subject to the foregoing, you must not:</p>
      <ul className={frontpageStyles.modalUl}>
        <li>Establish a link from any website that is not owned by you.</li>
        <li>Cause the Site or portions of it to be displayed on, or appear to be displayed by, any other site, for example, framing, deep linking, or in-line linking.</li>
        <li>Link to any part of the Site other than the homepage.</li>
        <li>Otherwise take any action with respect to the materials on the Site that is inconsistent with any other provision of these Terms.</li>
      </ul>
      <p>You agree to cooperate with us in causing any unauthorized framing or linking to immediately stop. We reserve the right to withdraw linking permission without notice.</p>
      <p>We may disable all or any social media features and any links at any time without notice in our discretion.</p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Links from the Site or Services</p>
      If the Site or Services contain links to other sites, services, products or resources provided by third parties, these links are provided for your convenience only. This includes links contained in advertisements, including banner advertisements and sponsored links. We have no control over the contents of those sites, services, products or resources, and accept no responsibility for them or for any loss or damage that may arise from your use of them. If you decide to access or use any of the third-party websites linked to the Site and Services, you do so entirely at your own risk and subject to the terms and conditions of use for such websites.
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Geographic Restrictions</p>
      <p>We provide the Site and Services for use only by persons located in the United States. We make no claims that the Site, the Services or any content is accessible or appropriate outside of the United States. Access to the Site and Services may not be legal by certain persons or in certain countries. If you access the Site or Services from outside the United States, you do so on your own initiative and are responsible for compliance with local laws.</p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Disclaimer of Warranties</p>
      <p>You understand that we cannot and do not guarantee or warrant that files available for downloading from the internet, including from the Site or Services, will be free of viruses or other destructive code. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for anti-virus protection and accuracy of data input and output, and for maintaining a means external to our site for any reconstruction of any lost data. To the fullest extent provided by law, we will not be liable for any loss or damage caused by a distributed denial-of-service attack, viruses, or other technologically harmful material that may infect your computer equipment, computer programs, data, or other proprietary material due to your use of the Site or Services, or items obtained through the Site or Services, including your downloading of any material posted on it, or on any site linked to it.</p>
      <p>Your use of the Site, its content, and the Services or items obtained through the Site or Services is at your own risk. The Site, its content, and the Services or items obtained through the Site or Services are provided on an &quot;as is&quot; and &quot;as available&quot; basis, without any warranties of any kind, either express or implied. Neither the Company nor any person associated with the Company makes any warranty or representation with respect to the completeness, security, reliability, quality, accuracy, or availability of the Site or Services. Without limiting the foregoing, neither the Company nor anyone associated with the Company represents or warrants that the Site, its content, the Services or items obtained through the Site or Services will be accurate, reliable, error-free, or uninterrupted, that defects will be corrected, that the Site, Services or the servers that makes the Site and Services available are free of viruses or other harmful components, or that the Site or Services or items obtained through the Site or Services will otherwise meet your needs or expectations. </p>
      <p>To the fullest extent provided by law, the Company hereby disclaims all warranties of any kind, whether express or implied, statutory, or otherwise, including but not limited to any warranties of merchantability, non-infringement, and fitness for particular purpose.</p>
      <p>The foregoing does not affect any warranties that cannot be excluded or limited under applicable law.</p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Limitation on Liability</p>
      <p>To the fullest extent provided by law, in no event will the Company, its affiliates, or their respective licensors, service providers, employees, agents, officers, or directors be liable for damages of any kind, under any legal theory, arising out of or in connection with your use, or inability to use, the Site, the Services any websites linked to them, any content on the Site, the Services or such other websites, including any direct, indirect, special, incidental, consequential, or punitive damages, including those arising from the loss of data or a data breach, loss of revenue, loss of profits, loss of business or anticipated savings, loss of use, loss of goodwill, loss of data, and whether caused by tort (including negligence), breach of contract, or otherwise, even if foreseeable. </p>
      <p>The limitation of liability set out above does not apply to liability resulting from our gross negligence or willful misconduct or death or bodily injury caused by products you purchase, whether or not through the Site or Services.</p>
      <p>THE FOREGOING DOES NOT AFFECT ANY LIABILITY THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.</p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Indemnification</p>
      <p>You agree to defend, indemnify, and hold harmless the Company, its affiliates, licensors, and service providers, and its and their respective officers, directors, employees, contractors, agents, licensors, suppliers, successors, and assigns from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys’ fees) arising out of or relating to (a) your violation of these Terms, (b) your use of the Site or Services other than as expressly authorized in these Terms, or (c) your use of any information, product or service obtained from or in connection with the Site or Services.</p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Feedback</p>
      <p>You may, from time to time, submit or recommend suggestions or feedback (<span class={commonStyles.bold}>&quot;Feedback&quot;</span>) to us that we may subsequently incorporate into the Site and/or Services. The Company, its affiliates, and its and their respective successors and assigns, may freely use, copy, disclose, sublicense, distribute, display and exploit any Feedback in connection with any products or services in any manner and without any obligation, payment, royalty or restriction based on intellectual property rights, confidentiality or otherwise. You hereby (a) grant the Company, its affiliates, and its and their respective successors and assigns a worldwide, non-exclusive, royalty-free, perpetual right and license to use and incorporate such Feedback into any product or service, including without limitation the Site and Services, and (b) acknowledge that, as between you and the Company, any product or service incorporating the Feedback will be the sole and exclusive property of the Company and all such Feedback will be free from any confidentiality restrictions that might otherwise be imposed on us. </p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Governing Law and Jurisdiction</p>
      <p>All matters relating to the Site, the Services and these Terms, and any dispute or claim arising therefrom or related thereto (in each case, including non-contractual disputes or claims), shall be governed by and construed in accordance with the internal laws of the State of Delaware without giving effect to any choice or conflict of law provision or rule (whether of the State of Delaware or any other jurisdiction).</p>
      <p>Any legal suit, action, or proceeding arising out of, or related to, these Terms, the Site or the Services shall be instituted exclusively in the federal courts of the United States or the courts of the State of Delaware, although we retain the right to bring any suit, action, or proceeding against you for breach of these Terms in your country of residence or any other relevant country. You waive any and all objections to the exercise of jurisdiction over you by such courts and to venue in such courts.</p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Arbitration</p>
      <p>At the Company’s sole discretion, it may require you to submit any disputes arising from these Terms, use of the Site or use of the Services, including disputes arising from or concerning their interpretation, violation, invalidity, non-performance, or termination, to final and binding arbitration under the Rules of Arbitration of the American Arbitration Association applying Delaware law.</p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Limitation on Time to File Claims</p>
      <p>ANY CAUSE OF ACTION OR CLAIM YOU MAY HAVE ARISING OUT OF OR RELATING TO THESE TERMS, THE SITE OR THE SERVICES MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES; OTHERWISE, SUCH CAUSE OF ACTION OR CLAIM IS PERMANENTLY BARRED.</p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Waiver and Severability</p>
      <p>No waiver by the Company of any term or condition set out in these Terms shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of the Company to assert a right or provision under these Terms shall not constitute a waiver of such right or provision.</p>
      <p>If any provision of these Terms is held by a court or other tribunal of competent jurisdiction to be invalid, illegal, or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of the Terms will continue in full force and effect. </p>
      <p className={`${commonStyles.typographyBodySemiBold} ${commonStyles.applyUnderline} ${frontpageStyles.modalMargin}`}>Your Comments and Concerns</p>
      <p>All feedback, comments, requests for technical support, and other communications relating to the Site and Services should be directed to: <a href='mailto:support@platformatic.dev?subject=General information about Terms of Usage'>support@platformatic.dev</a>, or</p>
      <p>Platformatic, Inc.</p>
      <p>548 Market St, Pmb 85033San Francisco, CA 94104</p>
    </div>
  )
}
