services:
  postgres:
    ports:
      - "127.0.0.1:5433:5432"
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: root
      PGDATA: /data/postgres
    volumes:
      - ./pg-init:/docker-entrypoint-initdb.d

  http-cache-valkey:
    ports:
      - "6342:6379"
    image: "valkey/valkey:8.1"


