packages:
  # all packages in direct subdirs of packages/
  - 'services/*'

supportedArchitectures:
  os:
    - darwin
    - linux

minimumReleaseAge: 1440

resolutionMode: highest

allowBuilds:
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  thread-cpu-usage: true
