-- Pattern-predictive scaler: adopt DERIVED ids and the candidate+accepted suggestions design.
--
-- Migrations 015-021 created the stats/prediction tables with RANDOM primary keys and a `suggestions`
-- table that held only ACCEPTED rows. The predictor since moved to:
--   * DERIVED ids  — every slot row's primary key is a uuidv5 of its natural key (see lib/ids.js), so a
--                    suggestion's calendar occurrences can be GENERATED instead of queried. The app
--                    supplies the id, so these columns must have no DB default.
--   * ONE suggestions table for CANDIDATES and ACCEPTED rows, told apart by `status`, keyed by a content
--     `identity` (uuidv5 of app + slot + sorted scope keys) rather than the raw (app, slot, scope_keys).
--
-- This migration transforms an existing 015-021 schema onto that design. The suggestions/scheduled_slots
-- rows are regenerated by the predictor and pre-production, so they are TRUNCATEd rather than migrated:
-- `identity` is an app-computed hash with no faithful SQL equivalent, so there is nothing to backfill.

-- Derived ids — the app supplies the primary key, so drop the random default.
ALTER TABLE time_slot_stats         ALTER COLUMN id DROP DEFAULT;
ALTER TABLE time_window_stats       ALTER COLUMN id DROP DEFAULT;
ALTER TABLE time_window_predictions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE scheduled_slots         ALTER COLUMN id DROP DEFAULT;

-- Suggestions: candidates + accepted in one table, keyed by content identity.
TRUNCATE scheduled_slots, suggestions;

ALTER TABLE suggestions ADD COLUMN identity uuid NOT NULL;
ALTER TABLE suggestions ADD COLUMN distribution JSONB NOT NULL DEFAULT '[]'::jsonb;

-- A candidate has no accepted_at and no forced status; both defaults on the accepted-only design go away.
ALTER TABLE suggestions ALTER COLUMN status      DROP DEFAULT;
ALTER TABLE suggestions ALTER COLUMN accepted_at DROP DEFAULT;
ALTER TABLE suggestions ALTER COLUMN accepted_at DROP NOT NULL;

-- 'suggested' (a candidate) joins the allowed states.
ALTER TABLE suggestions DROP CONSTRAINT suggestions_status;
ALTER TABLE suggestions ADD  CONSTRAINT suggestions_status
  CHECK (status IN ('suggested', 'active', 'cancelled', 'expired'));

-- Uniqueness moves onto the content identity, one row per OPEN status (a candidate and its accepted
-- copy share an identity; cancelled/expired history accumulates freely).
DROP INDEX suggestions_active_identity;
CREATE UNIQUE INDEX suggestions_one_candidate ON suggestions (identity) WHERE status = 'suggested';
CREATE UNIQUE INDEX suggestions_one_active    ON suggestions (identity) WHERE status = 'active';
CREATE INDEX        idx_suggestions_identity  ON suggestions (identity);
