export const APPLICATION_DETAILS_ALL_SERVICES = '/applications/:applicationId/services'
export const APPLICATION_DETAILS_ALL_SERVICES_DETAIL = '/applications/:applicationId/services/:serviceId'
export const APPLICATION_DETAILS_ALL_ACTIVITIES = '/applications/:applicationId/activities'
export const APPLICATION_DETAILS_SCHEDULED_JOBS = '/applications/:applicationId/scheduled-jobs'
export const APPLICATION_DETAILS_SCHEDULED_JOB_DETAIL = '/applications/:applicationId/scheduled-jobs/:id'
