# Allows the chart to install cloud-provider-specific resources
# Supported values: aws, gcp, dev, or empty
# The installation script will identify the correct value
cloud: ""

wattpro:
  # Configure monitoring of wattpro applications
  monitor:
    enable: true
    # The name of the Prometheus PodMonitor
    name: "wattpro"
    matchLabels:
      platformatic.dev/monitor: "prometheus"
    port: "metrics"

# Platformatic service configuration
# Installation documentation is available at:
services:

  icc:
    # Used in URLs and referencing deployments, pods, and secrets
    name: icc

    # Deploy ICC
    deploy: true

    # Monitor via Prometheus
    monitor:
      enabled: true

    # We have a changelog available at: 
    image:
      repository: platformatic/intelligent-command-center
      pullPolicy: Always
      tag: "latest"

    # Supported login methods
    # Change `enable` to `true` to use a method
    # At least one method must be enabled
    login_methods:
      google_oauth:
        enable: false
        client_id: ""
        client_secret: ""
      github_oauth:
        enable: false
        client_id: ""
        client_secret: ""

    # TODO Should provide a url to documentation for each feature
    features:
      cache_recommendations:
        enable: false
      risk_service_dump:
        enable: false
      ffc:
        enable: false
      icc_jobs:
        enable: true

    # Available levels: debug, info, warn, error
    log_level: warn

  machinist:
    # Used in URLs and for referencing deployments, pods, and secrets
    name: machinist

    # We have a changelog available at: 
    image:
      repository: platformatic/machinist
      pullPolicy: Always
      tag: "latest"

    # Set to false if machinist should not be installed
    deploy: true

    monitor:
      enabled: true

    serviceAccountName: "plt-pod-manager"

    # TODO Should provide a url to documentation for each feature
    features:
      event_export:
        enable: false

    # Available levels: debug, info, warn, error
    log_level: warn
