DROP TABLE IF EXISTS generations_deployments;
DROP TABLE IF EXISTS generations_applications_configs;
DROP TABLE IF EXISTS graphs;
DROP TABLE IF EXISTS detected_pods;
DROP TABLE IF EXISTS applications_configs;
DROP TABLE IF EXISTS deployments;
DROP TABLE IF EXISTS application_states;
DROP TABLE IF EXISTS applications;
DROP TABLE IF EXISTS generations;
